version: "3.7"
services:
  web-server:
    container_name: web4cacti
    build:
      dockerfile: web-server/Dockerfile
      context: .
      args:
        CACTI_VERSION: "${CACTI_VERSION:-1.2.24}"
    restart: always
    volumes:
      - "./data/html:/var/www/html"
      # - "web-cacti:/var/www/html"
    environment:
      CACTI_VERSION: "${CACTI_VERSION:-1.2.24}"
    ports:
      - "${CACTI_WEB_PORT:-8081}:80"

  mysql-server:
    container_name: mysql4cacti
    build:
      dockerfile: mysql-server/Dockerfile
      context: .
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
      # - mysql-data:/var/lib/mysql
    environment:
      CACTI_VERSION: "${CACTI_VERSION:-1.2.24}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-secret}"

# volumes:
#   web-cacti:
#   mysql-data: